name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: header
          token: ${{ secrets.GH_TOKEN }}
          config_timezone: America/Denver
          plugin_languages: yes
          config_order: base.header, languages
          filename: metrics.svg
          output_action: pull-request
          
